#!/usr/bin/env node
// Writes puzzles/traces-python.js: a step-by-step trace of every Python puzzle, recorded by running it
// under real Python (tools/trace.py, with sys.settrace). The daily page's "Step through it" plays it
// back after a game: the line about to run, the variables, and what's been printed so far.
//
//   npm run traces        (node tools/trace-puzzles.js)
//
// Run it after adding or changing a Python puzzle; the checker (tools/check-puzzles.js) fails a
// puzzle without an up-to-date trace. Traces are keyed by Debugg.codeId(code), so the order of the
// puzzles doesn't matter.
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { loadGame, ROOT } = require('./load-game');

const OUT = path.join(ROOT, 'puzzles/traces-python.js');

function traceAll(puzzles, D){
  const items = puzzles.map(p => ({ id: D.codeId(p.code), code: p.code }));
  const r = spawnSync('python3', [path.join(__dirname, 'trace.py')], { input: JSON.stringify(items), encoding: 'utf8', maxBuffer: 64 << 20, timeout: 120000 });
  if(r.error) throw r.error;
  if(r.status !== 0) throw new Error('trace.py failed:\n' + r.stderr);
  return JSON.parse(r.stdout);
}

if(require.main === module){
  const ctx = loadGame();
  // Code challenges (format 'pass') are the player's own code, so there's nothing to trace.
  const puzzles = ctx.DEBUGG_PUZZLES.filter(p => p.lang === 'python' && p.format !== 'pass');
  const traces = traceAll(puzzles, ctx.Debugg);
  const ordered = {};
  Object.keys(traces).sort().forEach(k => { ordered[k] = traces[k]; });
  fs.writeFileSync(OUT, '// Generated by tools/trace-puzzles.js (npm run traces): step-by-step traces of the Python puzzles,\n' +
    '// keyed by Debugg.codeId(code). Don\'t edit by hand.\n' +
    'window.DEBUGG_TRACES = Object.assign(window.DEBUGG_TRACES || {}, ' + JSON.stringify(ordered) + ');\n');
  const steps = Object.values(traces).reduce((n, t) => n + t.length, 0);
  console.log('Wrote ' + path.relative(ROOT, OUT) + ': ' + puzzles.length + ' puzzles, ' + steps + ' steps.');
}

module.exports = { traceAll };
